resources/js/components/AppHeader.vue

The className attribute was incorrectly used in the Vue template, which caused styling issues. This change replaces className with the correct class attribute to ensure proper styling and alignment with Vue's syntax. No breaking changes are introduced.

fix: correct className to class in AppHeader.vue

---

resources/js/components/AppearanceTabs.vue

When running `npm run build` or `npm run dev`, we are getting this warning:
```
npm run build                                                                                   ✔  01:04:13 PM 
> build
> vite build
vite v6.1.1 building for production...
transforming (1460) node_modules/lucide-vue-next/dist/esm/icons/sunset.js[@vue/compiler-sfc] withDefaults() is unnecessary when using destructure with defineProps().
Reactive destructure will be disabled when using withDefaults().
Prefer using destructure default values, e.g. const { foo = 1 } = defineProps(...).
/Users/tony/Herd/vue-starter-kit/resources/js/components/AppearanceTabs.vue
7  |  }
8  |
9  |  const { class: containerClass } = withDefaults(defineProps<Props>(), {
|                                    ^^^^^^^^^^^^
10 | …
```

fixing the warning message

---

resources/js/components/AppHeader.vue
resources/js/components/AppSidebar.vue
resources/js/components/NavFooter.vue

This pull request renames the url property to href to align with the NavItem interface definition.
The current NavItem interface is structured as follows, and it does not include a url property, necessitating this change:
```
export interface NavItem {
title: string;
href: string;
icon?: LucideIcon;
isActive?: boolean;
}
```
By updating url to href, we ensure consistency with the existing type definition and avoid potential issues related to property mismatches.

Rename url to href in navigation items for consistency

---

resources/js/pages/auth/Login.vue
resources/js/pages/auth/Register.vue

Fix the console warnings below when you navigate to either register or login page
`[Vue warn]: Invalid prop: type check failed for prop "tabindex". Expected Number with value 6, got String with value "6".
`

Fix console warning messages on the login and register pages

---

resources/js/components/NavMain.vue

At the moment the sidebar links are not functioning at all. 
This pull request fixes the type error in `AppSidebar.vue` by using the imported `NavItem` type and correct property names in `NavMain.vue`.

Fix sidebar functionality by using correct type in NavMain

---

resources/js/pages/settings/Profile.vue

The autocomplete attribute for the email input field was incorrectly set to "username". This change updates it to "email" to ensure proper browser autofill behavior and improve user experience. No breaking changes are introduced.

fix: update autocomplete attribute in Profile.vue

---

app/Http/Middleware/HandleInertiaRequests.php

I am not sure why `array_merge()` is used with the array spread operator. It may not be necessary. Can't we simply use the array spread operator?
Before
```php
return array_merge(parent::share($request), [
...parent::share($request),
'name' => config('app.name'),
'quote' => ['message' => trim($message), 'author' => trim($author)],
'auth' => [
'user' => $request->user(),
],
]);
```
After
```php
return [
...parent::share($request),
'name' => config('app.name'),
'quote' => ['message' => trim($message), 'author' => trim($author)],
'auth' => [
'user' => $request->user(),
],
];
```

Remove redundant prop sharing from the middleware

---

resources/js/pages/settings/Password.vue

This PR updates the initialization of `ref<HTMLInputElement>` references by explicitly setting them to `null`.  
- Updated `ref<HTMLInputElement>()` to `ref<HTMLInputElement | null>(null)`, ensuring proper type safety.  
- Prevents potential runtime errors by making sure `passwordInput.value` and `currentPasswordInput.value` are never `undefined`.  
- Aligns with Vue best practices for handling template refs.  
- Without explicit `null`, TypeScript infers `undefined`, leading to potential issues when accessing `.value`.  
- Ensures better predictability and avoids unnecessary runtime checks.  
This change improves overall code reliability and maintainability.

Fix: Explicitly Initialize Input Refs with null for Better Type Safety

---

resources/js/components/AppHeader.vue
resources/js/components/AppSidebarHeader.vue
resources/js/components/Breadcrumbs.vue
resources/js/layouts/AppLayout.vue

This PR fix breadcrumb not displayed due to unknown breadcrumb component loaded in the `AppHeader.vue ` for the **Header Layout**.
Add 2 items in the breadcrumb items on the any page component.
Then it will display the breadcrumb

Fix: Breadcrumb not displayed on the header layout

---

resources/js/components/DeleteUser.vue

This PR fixes the gap issue in the buttons of the DeleteUser component.
**Before:**
**After:**

fix: add gap to DialogFooter in DeleteUser component

---

resources/js/components/AppHeader.vue

This PR fix browser console warning when `AvatarImage` component src prop was undefined. 
Uses Same as logic from `UserInfo` component but without using computed property

Fix: Vue type checking for `AvatarImage` component

---

package-lock.json
package.json

With the included vite `^6.0.3` dependency, there is a vulnerability with its own esbuild dependency. This PR updates vite to `^6.2.0`, which mitigated it by updating esbuild to `^0.25.0` in https://github.com/vitejs/vite/pull/19389.
Below is the warning before this PR:
```js
esbuild  <=0.24.2
Severity: moderate
esbuild enables any website to send any requests to the development server and read the response - https://github.com/advisories/GHSA-67mh-4wv8-2f99
fix available via `npm audit fix`
node_modules/esbuild
vite  0.11.0 - 6.1.1
Depends on vulnerable versions of esbuild
node_modules/vite
2 moderate severity vulnerabilities
To address all issues, run:
npm audit fix
```

Fix: esbuild vulnerability

---

resources/js/types/index.ts

The ziggy prop is not returned from the backend and is not being used anywhere

Remove unused element

---

resources/js/types/index.ts

I notice this type issue:
I am not sure why `ShareData` doesn't satisfy `PageProps` since `PageProps` is of type ` { [k: string]: unknown } `. But with this PR it seems to be fixed.

Fix ShareData type

---

resources/js/pages/settings/Profile.vue

Resolved incorrect styles in dark mode while settings/profile worked fine in light mode.

Fix styles for update profile with dark mode

---

resources/js/components/Breadcrumbs.vue

Since the goal is to avoid a full-page reload for breadcrumbs and the type is optional, why not use a fallback route as well.

Refactor: use Inertia Link with fallback in Breadcrumbs component

---

resources/js/components/Breadcrumbs.vue

Without `as-child`, this will render double nested `<a>` tags.

fix: double anchor tag in Breadcrumbs

---

resources/js/app.ts

The import path for ZiggyVue has been updated from
Before
```
import { ZiggyVue } from '../../vendor/tightenco/ziggy';
```
After
```
import { ZiggyVue } from 'ziggy-js';
```
This change aligns with the updated package structure and ensures compatibility with the latest version of the Ziggy library. No breaking changes are introduced as the functionality remains the same.

refactor: Update ZiggyVue import path to use 'ziggy-js'

---

resources/js/types/index.ts

The import statements in the file resources/js/types/index.ts have been reordered.
The change was a result of running  `npm run format`

chore: reorder imports in resources/js/types/index.ts

---

resources/js/components/AppHeader.vue

This PR fixes the active indicator in the AppHeader navigation. Currently it's always present below each link. With the PR it's the same behaviour as in the React starter kit and just shown, when the the nav link is active.

Fix: Active indicator in app header layout

---

.gitignore

Great work with these kits! One minor thing, looks like the `bootstrap/ssr` folder isn't being ignored by source control. Added that folder to the `.gitignore` file to fix that.
Same [change](https://github.com/laravel/react-starter-kit/pull/50) can be found in the React starter kit as well.

Remove SSR folder from source control

---

resources/js/components/AppHeader.vue

The AppLogo component on the AppHeaderLayout, can not have a class because the component does not have a single root element.

AppLogo class fixed

---

routes/settings.php

This PR updates the `Route::redirect` for the `settings` route to include a leading slash in the destination path. Previously, the redirect caused issues when accessing `/settings/` with a trailing slash, as Laravel would not properly resolve the relative path.
**Testing:**
- Visit `/settings` → should redirect correctly.
- Visit `/settings/` → should now also redirect correctly.
- Confirm that `/settings/profile` loads as expected.

Fix Route Redirect for Settings Path

---

.prettierignore

The included GitHub test workflow runs `php artisan ziggy:generate` which creates the `resources/js/ziggy.js` file. This generated file would have its formatting changed when running Prettier with the included config.
This means that if the user adds a formatting check as part of their test workflow (e.g. `prettier --check`) it will fail.
As the file is auto-generated there should not be any issues ignoring it when manually running Prettier outside of the test workflow.

Ignore ziggy.js in Prettier

---

resources/js/components/Heading.vue

Aligns the design with the react starter kit as per laravel/react-starter-kit#60

Remove the separator under the heading

---

.prettierignore

This PR adds a new rule to `.prettierignore` to exclude `resources/views/mail/*` from automatic formatting. Email templates often contain embedded Blade syntax and inline styles, which Prettier's formatting rules can disrupt. Ignoring these files ensures that the email templates' intended structure and formatting remain intact.

Add a `.prettierignore` rule to exclude `resources/views/mail/*` from formatting.

---

package-lock.json
package.json
resources/js/pages/settings/Password.vue
resources/js/pages/settings/Profile.vue

Vue has built in transition components, no need to have a package for this. (the package is for more complex transitions, i.e. nested child transitions from a single root component)

Replace headlessui transition with vue built-in

---

resources/js/components/NavUser.vue

This update aligns the vue-starter-kit with react-starter-kit regarding the sidebar dropdown

fix: sidebar dropdown open position

---

app/Http/Middleware/HandleInertiaRequests.php
bootstrap/app.php
resources/js/components/AppShell.vue
resources/js/components/ui/sidebar/utils.ts
resources/js/types/index.d.ts

Shadcn includes [built-in functionality](https://www.shadcn-vue.com/docs/components/sidebar.html#persisted-state) to determine the sidebar state via cookie, so the local component logic utilizing local storage is unnecessary. I've also renamed the cookie name in `utils.ts` to reflect what's in the documentation.
This change is the Vue version of the same change being made to the [React](https://github.com/laravel/react-starter-kit/pull/72) starter kit.

Use shadcn built-in check for sidebar state

---

resources/js/components/UserMenuContent.vue

This PR is related to this React Starter Kit PR: https://github.com/laravel/react-starter-kit/pull/97,
This actually was not an issue in the Vue starter kit because we didn't have the `prefetch` attribute on the Settings link; however, to keep things consistent I've added the prefetch attribute as well as the `router.flushAll()` when the user logs out.

Adding prefetch to settings and adding logout flush

---

app/Http/Middleware/HandleInertiaRequests.php
bootstrap/app.php

In shadcn-vue docs they mention that SIDEBAR_COOKIE_NAME is `sidebar_state` but in the actual code in [sidebar/utils.ts](https://github.com/unovue/shadcn-vue/blob/e5fbf5f5553b8e58a32625291540b94c8fc8cb87/apps/www/src/registry/default/ui/sidebar/utils.ts#L4) it's `sidebar:state` (with semicolon)
Without this fix, the sidebar looses its state everytime the user navigates to a different page or refreshes the page.

Sidebar state fix

---

resources/js/pages/auth/Login.vue

This PR fixes an issue with a `tabindex` attribute being on the `<div>` element around the "Remember me" checkbox, which provides no functionality when being tab-focused (and trying to enter/space to toggle).
The React starter kit doesn't have this issue.
With this fix, the tab focus behaviour matches the one of the React starter kit on the Login Form.
Before:
After (one less tab-press):

Fix `tabindex` focus issue on Login Page

---

package.json

This removes `lucide` lib, since `lucide-vue-next` is the oficial way to use lucide in vue and it is already installed https://lucide.dev/guide/packages/lucide-vue-next

remove lucide lib

---

README.md

Reverts laravel/vue-starter-kit#119

Revert "Update README to reflect migration to Reka UI"

---

resources/js/components/ui/sidebar/utils.ts

Change SIDEBAR_COOKIE_NAME to `sidebar_state` as mentioned in https://github.com/laravel/vue-starter-kit/pull/106.

fix(sidebar): Update SIDEBAR_COOKIE_NAME

---

resources/js/components/Breadcrumbs.vue

The name BreadcrumbItem it's conflicting with component and type.

fix: handle conflicting variable with same name

---

resources/css/app.css

I feel this is redundant code that was left by accident when adding `outline-ring/50` to the base layer?
Originally added by @tnylea in PR #93, maybe you can shine some light on it if it was deliberate.

Remove redundant `@layer base` from app.css

---

resources/js/components/DeleteUser.vue

In `DeleteUser.vue` dialog the submit (Delete account) button is nested inside another submit button.
This PR removes the extra nested button.

Remove nested submit button

---

resources/js/components/AppHeader.vue

Like [react-starter-kit](https://github.com/laravel/react-starter-kit/blob/a112a23e1a54c59a91036b781ce686ec54e35262/resources/js/components/app-header.tsx#L107), don't use NavigationMenuLink inside Link
Before:
After:

ui: fix AppHeader menu item

---

resources/js/components/ui/sidebar/SidebarInset.vue

The margin adjustment for the layout when the sidebar is collapsed was unintentionally overridden by a recent update. This commit restores the previous fix by @tnylea  to ensure the sidebar looks symmetrical when it's collapsed.
See Similar PR: https://github.com/laravel/react-starter-kit/pull/64

Fix layout margin issue when sidebar is collapsed, after override by recent update

---

package-lock.json
resources/js/app.ts
resources/js/components/AppShell.vue
resources/js/components/NavMain.vue
resources/js/components/NavUser.vue
resources/js/components/UserInfo.vue
resources/js/pages/Welcome.vue
resources/js/pages/settings/Profile.vue
resources/js/ssr.ts
resources/js/types/globals.d.ts
resources/js/types/index.d.ts
resources/js/types/ziggy.d.ts
tsconfig.json
vite.config.ts

This pull request simplifies type usage, removes unused imports, and improves the SSR setup.
While following the Ziggy-JS setup guide, I noticed that our ssr.ts file does a lot of unnecessary work. We can replace most of it with the ziggyVue plugin. We also don’t need the Ziggy alias pointing to the vendor directory, since Ziggy is already installed as a JS dependency. Finally, I added proper Vue-specific route definitions.
- SharedProps: Refactored to extend and override the package’s App props, so we can use the usePage helper without manually declaring prop types each time.
- Inertia helpers: Added missing type definitions for Inertia helper functions used in template files.
- tsconfig.json: Removed the non-existent `vue/tsx` entry from the types array. It wasn’t provided by any …

Fix various TypeScript issues, simplify ziggy-js integration and shared props usage

---

vite.config.ts

I recently learned that the [laravel-vite-plugin](https://github.com/laravel/vite-plugin/blob/1.x/src/index.ts#L122) registers the same @ alias already (https://github.com/laravel/vite-plugin/blob/4a1c05598cc9fd14a26ceb9a125fee17fb828002/src/index.ts#L122) We can omit it in vite.config.ts and simply the config a bit more.

Simplify vite.config.ts by removing the "duplicate" @ alias

---

routes/auth.php
routes/settings.php

Following up from https://github.com/laravel/vue-starter-kit/pull/157, fair point that the non-authenticated routes in that PR would throttle via IP, which makes them a risk. The _Confirm Password_ and _Password Change_ routes, on the other hand, are both authenticated so the throttle will work based on the User Identifier instead. 
Rate limiting these routes is important because they are vulnerable to brute-force attacks if a user's session is hijacked. An attacker who gains access to a user account, can brute-force the user's password to bypass the verification step, or change the password entirely. This would bypass any brute-force monitoring or protections present on the login form.
The risk is relatively low, as an attacker would need to have hijacked the user's account, but it's …

Add throttle to authed password routes

---

resources/js/layouts/settings/Layout.vue

The space-y was not necessary on smaller screens since we are using a Separator component. I also updated the separator to hide on lg and above since the container element changes to flex row at that breakpoint.

Update Settings Layout- Remove y spacing and update break for Separator

---

.prettierrc

Prettier sort class inside `class` and `:class` attributes.
In .prettierrc, we have `clsx` and `cn` inside `tailwindFunctions`, but `cva` is missing.
Adding `cva` will sort classes inside those functions too !

fix: add cva in tailwindFunctions for prettier class sorting

---

components.json

As @patrickdundas highlighted in [#166](https://github.com/laravel/vue-starter-kit/pull/166), the transition from `typescript` to `tsx` in the vue-starter-kit has introduced an issue that breaks the ability to add components via the CLI.
Upon further investigation, @patrickdundas found that the root of the issue lies in how components.json is handled differently between the shadcn and shadcn-vue packages:
shadcn-vue defaults to using `typescript` in its schema.
shadcn, on the other hand, defaults to `tsx`.
When reverting the `tsx` setting back to the `typescript` and setting it to true, component generation works as expected, but not for 3rd party plugins. However, if you then attempt to set typescript to false, it breaks the generation process again.
This makes the setting somewhat …

Remove TSX from components.json

---

resources/js/ssr.ts

I noticed that across all our starter kits, old and new, the SSR bootstrap file was the only place that had an extracted method for the resolve function.
This aligns the function logic across starter kits and also within this repo itself, as this now aligns with the `app.ts` bootstrap function.

Standardise function usage

---

resources/js/components/DeleteUser.vue

Addresses the same issue as #161 without adjusting the `Input` component.

Fix password input focus error

---

tests/Feature/Auth/AuthenticationTest.php
tests/Feature/Auth/EmailVerificationTest.php
tests/Feature/Auth/PasswordResetTest.php
tests/Feature/Auth/VerificationNotificationTest.php
tests/Feature/Settings/PasswordUpdateTest.php

This PR adds feature tests that were previously untested in the starter kit. With these additions, a freshly generated application now reaches **100% test coverage** out of the box. For example, if someone run pest with 100% coverage:
```bash
pest --parallel --coverage --exactly=100
```
will pass successfully on a clean install. This means developers start with full coverage by default, without having to write additional tests themselves.
Not everyone needs 100% coverage for their project, but having it baked into the starter kit provides a solid foundation to build from. Teams can then decide whether to maintain this level or adjust it to match their specific requirements.
The following authentication and verification scenarios are now covered by tests:
* Users are rate limited after …

test: Add missing feature tests to ensure 100% coverage in starter kit

---

resources/js/components/AppHeader.vue
resources/js/components/NavFooter.vue
resources/js/components/NavMain.vue
resources/js/layouts/settings/Layout.vue
resources/js/lib/utils.ts

This pull request fixes the way active navigation items are determined in the `NavMain.vue` component. The main change is the introduction of a new `isActive` helper function, which handles both string and object types for the `href` property.
Navigation logic improvement:
* Added an `isActive` function to correctly determine if a navigation item is active by handling both string and object `href` types, and updated the `SidebarMenuButton` to use this function for its `is-active` prop.

Fix active state logic for sidebar menu items

---

app/Http/Requests/Auth/LoginRequest.php

The issue was caused by a too-strict PHPDoc that assumed the retrieved user is always a User. However, `retrieveByCredentials()` can return null. 
This aligns the docblock with the actual return type, making the subsequent null/credential checks type-safe.

Correct LoginRequest retrieved user type to allow null
